version: '3.8' # Specifies the Docker Compose file version

services:
  openapi-mcp:
    # Build the image using the Dockerfile located in the parent directory
    build:
      context: .. # The context is the parent directory (project root)
      dockerfile: Dockerfile # Explicitly points to the Dockerfile
    image: openapi-mcp-example-weather-compose:latest # Optional: Name the image built by compose
    container_name: openapi-mcp-example-weather-service # Sets a specific name for the container

    ports:
      # Map port 8080 on the host to port 8080 in the container
      - "8080:8080"

    volumes:
      # Mount the local './weather' directory (relative to this compose file)
      # to '/app/example/weather' inside the container.
      # This makes the spec file accessible to the application.
      - ./weather:/app/example/weather

    # Load environment variables from the .env file located in ./weather
    # This is the recommended way to handle secrets like API keys.
    # Ensure 'example/weather/.env' exists and defines API_KEY.
    env_file:
      - ./weather/.env

    # Define the command to run inside the container, overriding the Dockerfile's CMD/ENTRYPOINT args
    # Uses the variables loaded from the env_file.
    # Make sure the --spec path matches the volume mount point.
    command: >
      --spec /app/example/weather/weatherbitio-swagger.json
      --api-key-env API_KEY
      --api-key-name key
      --api-key-loc query
      --port 8080 # The port the app listens on inside the container

    # Restart policy: Automatically restart the container unless it was manually stopped.
    restart: unless-stopped 